apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
  labels:
    app: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-demo
        image: 192.168.4.219/demo/init:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
